### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by koomie** [pecos/tps#77]
* [x] - land on `main` and confirm successful CI tests
* [x] - update CHANGES with release notes and date
* [x] - tag code repo
* [x] - tag docs repo (matching the code repo tag)
* [x] - upload distribution tarball to release
